[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -D USE_SIMULATED_SENSORS=1

lib_deps =
    256dpi/MQTT@2.5.3


[env:native]
platform = native

build_flags =
    -std=c++17
    -Iinclude

test_framework = unity
build_src_filter = +<validator.cpp>
test_build_src = yes
test_filter = test_validator


[env:native-flow]
platform = native

build_flags =
    -std=c++17
    -Iinclude
    -Itest/stubs
    -D USE_SIMULATED_SENSORS=1

test_framework = unity

build_src_filter =
    +<sensor_manager.cpp>
    +<validator.cpp>

test_build_src = yes
test_filter = test_data_flow
